/*jslint node: true */
"use strict";

var campaignHelper = require('../js/campaign_helper.js');
var ethConnector = require('ethconnector');
var fs = require('fs');
var path = require('path');
var async = require('async');


var initialSupply = 1000000;

ethConnector.init('rpc', function(err) {
    if (err) {
        console.log("ERROR starting rpc: " + err);
        process.exit(1);
    }
    var now = Math.floor(new Date().getTime() /1000);

    campaignHelper.deploy({
        owners: [
            "0xC2d9F9c9dD6f76784a8f56f936953b6661A12da8",   // AP
            "0x6b42907e8eee04eb419ba99c8dda8cc3b8e1a504",   // BW
            "0x839395e20bbb182fa440d08f850e6c7a8f6f0780",   // Griff
            "0x82aEB1D8939f514318449fa8Ec704A94DC16E01D",   // Gian
            "0x1dba1131000664b884a1ba238464159892252d3a"    // Jordi
        ],
        required: 2,
        startFundngTime: now - 5*60,
        endFundingTime: now + 86400*120,
        maximumFunding: ethConnector.web3.toWei(10000)
    }, function(err, _vault, _campaign, _campaignToken, _compilationResult) {
        if (err) {
            console.log("ERROR deploying: " + err);
            process.exit(1);
        }

        console.log("vault contract address: " + _vault.address);
        console.log("campaign address: " + _campaign.address);
        console.log("campaign token address: " + _campaignToken.address);

        async.series([
            function(cb) {
                fs.writeFile('wallet_deployed.sol', _compilationResult.srcWallet, cb);
            },
            function(cb) {
                fs.writeFile('campaign_deployed.sol', _compilationResult.srcCampaign, cb);
            },
            function(cb) {
                saveFile(_vault, _campaign, _campaignToken, _compilationResult, cb);
            }
        ], function(err) {
            if (err) {
                console.log("ERROR writing file: " + err);
                process.exit(1);
            }
            process.exit(0);
        });
    });

});


function saveFile(_vault, _campaign, _campaignToken,_compilationResult, cb) {

    var S ='';
    S += '/*jslint node: true */\n';
    S += '"use strict";\n';
    S += '\n';
    S += '// This file is automatically generated every time you deploy the contract\n';
    S += '\n';
    S += 'var ethConnector = require("ethconnector"); \n';
    S += '\n';
    S += 'ethConnector.on("init", function() {\n';
    S += '  exports.vaultAbi = '+  _compilationResult.Wallet.interface + ';\n';
    S += '  exports.campaignAbi = '+  _compilationResult.Campaign.interface + ';\n';
    S += '  exports.campaignTokenAbi = '+  _compilationResult.CampaignToken.interface + ';\n';
    S += '\n';
    S += '  exports.vault = ethConnector.web3.eth.contract(exports.vaultAbi).at("' + _vault.address+ '");\n';
    S += '  exports.campaign = ethConnector.web3.eth.contract(exports.campaignAbi).at("' + _campaign.address+ '");\n';
    S += '  exports.campaignToken = ethConnector.web3.eth.contract(exports.campaignTokenAbi).at("' + _campaignToken.address+ '");\n';
    S += '});\n';

    async.series([
        function(cb) {
            fs.stat(path.join(__dirname, 'contracts.js'), function(err, stat) {
                if (err) return cb();
                fs.rename(path.join(__dirname,'contracts.js'), path.join(__dirname,'contracts_') + stat.birthtime.toISOString() + '.js', cb);
            });
        },
        function(cb) {
            fs.writeFile(path.join(__dirname,'contracts.js'), S, cb);
        }
    ], cb);
}
